package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	args := os.Args[1:]
	if len(args) > 0 && args[0] == "--" {
		args = args[1:]
	}
	if len(args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: %s <output.go> <charset>...\n", os.Args[0])
		os.Exit(1)
	}
	outFile := args[0]
	charsets := args[1:]

	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString("package utf\n\n")

	for _, cs := range charsets {
		arr, err := parseCharset(cs)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error parsing %s: %v\n", cs, err)
			os.Exit(1)
		}
		// write array
		varName := cs + "_to_UTF32"
		out.WriteString(fmt.Sprintf("var %s = [%d]rune{\n", varName, len(arr)))
		for i, r := range arr {
			if i%8 == 0 {
				out.WriteString("    ")
			}
			out.WriteString(fmt.Sprintf("0x%04X, ", r))
			if i%8 == 7 {
				out.WriteString("\n")
			}
		}
		if len(arr)%8 != 0 {
			out.WriteString("\n")
		}
		out.WriteString("}\n\n")

		// reverse map
		mapName := "UTF32_to_" + cs
		out.WriteString(fmt.Sprintf("var %s = map[rune]byte{\n", mapName))
		for i, r := range arr {
			if r == rune(i) {
				continue // identical mapping
			}
			out.WriteString(fmt.Sprintf("    0x%04X: 0x%02X,\n", r, i))
		}
		out.WriteString("}\n\n")
	}

	if err := os.WriteFile(outFile, []byte(out.String()), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func parseCharset(cs string) ([]rune, error) {
	path := filepath.Join("include", "Tutf", strings.ToLower(cs)+".h")
	if _, err := os.Stat(path); err != nil {
		path = filepath.Join("..", "include", "Tutf", strings.ToLower(cs)+".h")
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	constRe := regexp.MustCompile(`^#define\s+T_` + regexp.QuoteMeta(cs) + `_(\S+)\s+0x([0-9A-Fa-f]+)`)
	listStart := "#define T_LIST_" + cs + "(EL)"

	constants := map[string]int{}
	var list []string
	scanner := bufio.NewScanner(f)
	inList := false
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if m := constRe.FindStringSubmatch(line); m != nil {
			val, _ := strconv.ParseInt(m[2], 16, 32)
			constants[m[1]] = int(val)
			continue
		}
		if strings.HasPrefix(line, listStart) {
			inList = true
			continue
		}
		if inList {
			if strings.HasPrefix(line, "/*") {
				continue
			}
			if strings.HasPrefix(line, "#") {
				if strings.HasPrefix(line, "#define") {
					inList = false
				}
				continue
			}
			if idx := strings.Index(line, "EL("); idx >= 0 {
				start := idx + len("EL(")
				end := strings.Index(line[start:], ")")
				if end >= 0 {
					name := strings.TrimPrefix(line[start:start+end], "_")
					list = append(list, name)
				}
			}
			if !strings.HasSuffix(line, "\\") {
				inList = false
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(list) == 0 {
		return nil, fmt.Errorf("no list found in %s", path)
	}
	arr := make([]rune, len(list))
	fmt.Fprintf(os.Stderr, "parsed %s: %d entries\n", cs, len(list))
	for i, name := range list {
		val, ok := constants[name]
		if !ok {
			return nil, fmt.Errorf("constant %s_%s not found", cs, name)
		}
		arr[i] = rune(val)
	}
	return arr, nil
}
